// Auto-generated by scripts/generate_turn_taking_data.py — do not edit manually

export interface TurnLabelPcts {
  onTime: number;
  late: number;
  early: number;
  indeterminate: number;
}

export interface LateTurnBreakdown {
  withToolCalls: number;
  withoutToolCalls: number;
}

export interface TurnTakingEntry {
  systemId: string;
  allTurns: TurnLabelPcts;
  toolCallTurns: TurnLabelPcts;
  noToolCallTurns: TurnLabelPcts;
  latePctWithToolCalls: number;
  latePctWithoutToolCalls: number;
  latePctDifference: number;
  lateTurnBreakdown: LateTurnBreakdown;
}

export const turnTakingData: TurnTakingEntry[] = [
  {
    systemId: 'gpt-realtime-mini',
    allTurns: { onTime: 79.1, late: 19.9, early: 1.0, indeterminate: 0.0 },
    toolCallTurns: { onTime: 76.4, late: 23.0, early: 0.6, indeterminate: 0.0 },
    noToolCallTurns: { onTime: 83.0, late: 15.2, early: 1.7, indeterminate: 0.0 },
    latePctWithToolCalls: 23.0,
    latePctWithoutToolCalls: 15.2,
    latePctDifference: 7.8,
    lateTurnBreakdown: { withToolCalls: 69.5, withoutToolCalls: 30.5 },
  },
  {
    systemId: 'voxtral-mini-3b-gpt-oss-120b-magpie',
    allTurns: { onTime: 67.3, late: 25.1, early: 7.4, indeterminate: 0.1 },
    toolCallTurns: { onTime: 49.4, late: 47.0, early: 3.6, indeterminate: 0.0 },
    noToolCallTurns: { onTime: 77.5, late: 12.7, early: 9.6, indeterminate: 0.2 },
    latePctWithToolCalls: 47.0,
    latePctWithoutToolCalls: 12.7,
    latePctDifference: 34.3,
    lateTurnBreakdown: { withToolCalls: 67.8, withoutToolCalls: 32.2 },
  },
  {
    systemId: 'gpt-4o-mini-transcribe-gpt-oss-120b-gpt-4o-mini-tts',
    allTurns: { onTime: 62.0, late: 34.7, early: 3.1, indeterminate: 0.1 },
    toolCallTurns: { onTime: 41.4, late: 56.2, early: 2.1, indeterminate: 0.3 },
    noToolCallTurns: { onTime: 72.0, late: 24.3, early: 3.7, indeterminate: 0.0 },
    latePctWithToolCalls: 56.2,
    latePctWithoutToolCalls: 24.3,
    latePctDifference: 31.9,
    lateTurnBreakdown: { withToolCalls: 52.9, withoutToolCalls: 47.1 },
  },
  {
    systemId: 'whisper-large-v3-gpt-oss-120b-kokoro',
    allTurns: { onTime: 60.2, late: 35.4, early: 4.2, indeterminate: 0.2 },
    toolCallTurns: { onTime: 36.3, late: 61.7, early: 2.1, indeterminate: 0.0 },
    noToolCallTurns: { onTime: 73.9, late: 20.4, early: 5.4, indeterminate: 0.3 },
    latePctWithToolCalls: 61.7,
    latePctWithoutToolCalls: 20.4,
    latePctDifference: 41.3,
    lateTurnBreakdown: { withToolCalls: 63.3, withoutToolCalls: 36.7 },
  },
  {
    systemId: 'voxtral-mini-3b-gpt-oss-20b-magpie',
    allTurns: { onTime: 60.1, late: 35.8, early: 4.0, indeterminate: 0.2 },
    toolCallTurns: { onTime: 42.1, late: 52.6, early: 5.1, indeterminate: 0.2 },
    noToolCallTurns: { onTime: 73.7, late: 23.1, early: 3.1, indeterminate: 0.2 },
    latePctWithToolCalls: 52.6,
    latePctWithoutToolCalls: 23.1,
    latePctDifference: 29.5,
    lateTurnBreakdown: { withToolCalls: 63.4, withoutToolCalls: 36.6 },
  },
  {
    systemId: 'gpt-4o-mini-transcribe-gpt-oss-20b-gpt-4o-mini-tts',
    allTurns: { onTime: 53.8, late: 43.5, early: 2.5, indeterminate: 0.2 },
    toolCallTurns: { onTime: 35.5, late: 61.1, early: 3.1, indeterminate: 0.2 },
    noToolCallTurns: { onTime: 66.3, late: 31.5, early: 2.1, indeterminate: 0.1 },
    latePctWithToolCalls: 61.1,
    latePctWithoutToolCalls: 31.5,
    latePctDifference: 29.7,
    lateTurnBreakdown: { withToolCalls: 56.9, withoutToolCalls: 43.1 },
  },
  {
    systemId: 'ultravox-realtime',
    allTurns: { onTime: 52.9, late: 40.8, early: 6.1, indeterminate: 0.3 },
    toolCallTurns: { onTime: 29.1, late: 65.3, early: 5.1, indeterminate: 0.4 },
    noToolCallTurns: { onTime: 90.8, late: 1.4, early: 7.8, indeterminate: 0.0 },
    latePctWithToolCalls: 65.3,
    latePctWithoutToolCalls: 1.4,
    latePctDifference: 63.9,
    lateTurnBreakdown: { withToolCalls: 98.7, withoutToolCalls: 1.3 },
  },
  {
    systemId: 'parakeet-ctc-1-1b-gpt-oss-120b-magpie',
    allTurns: { onTime: 45.7, late: 51.1, early: 3.0, indeterminate: 0.1 },
    toolCallTurns: { onTime: 27.2, late: 70.7, early: 2.1, indeterminate: 0.0 },
    noToolCallTurns: { onTime: 61.2, late: 34.8, early: 3.8, indeterminate: 0.3 },
    latePctWithToolCalls: 70.7,
    latePctWithoutToolCalls: 34.8,
    latePctDifference: 35.9,
    lateTurnBreakdown: { withToolCalls: 62.9, withoutToolCalls: 37.1 },
  },
  {
    systemId: 'parakeet-ctc-1-1b-gpt-oss-20b-magpie',
    allTurns: { onTime: 42.5, late: 56.5, early: 0.8, indeterminate: 0.1 },
    toolCallTurns: { onTime: 22.2, late: 76.6, early: 1.2, indeterminate: 0.0 },
    noToolCallTurns: { onTime: 61.9, late: 37.4, early: 0.5, indeterminate: 0.2 },
    latePctWithToolCalls: 76.6,
    latePctWithoutToolCalls: 37.4,
    latePctDifference: 39.1,
    lateTurnBreakdown: { withToolCalls: 66.1, withoutToolCalls: 33.9 },
  },
  {
    systemId: 'ultravox-v0-7-kokoro',
    allTurns: { onTime: 36.5, late: 58.2, early: 5.0, indeterminate: 0.3 },
    toolCallTurns: { onTime: 16.9, late: 77.9, early: 4.7, indeterminate: 0.5 },
    noToolCallTurns: { onTime: 67.9, late: 26.7, early: 5.4, indeterminate: 0.0 },
    latePctWithToolCalls: 77.9,
    latePctWithoutToolCalls: 26.7,
    latePctDifference: 51.2,
    lateTurnBreakdown: { withToolCalls: 82.3, withoutToolCalls: 17.7 },
  },
  {
    systemId: 'voxtral-mini-3b-qwen3-5-27b-kokoro',
    allTurns: { onTime: 38.1, late: 59.9, early: 1.7, indeterminate: 0.3 },
    toolCallTurns: { onTime: 18.2, late: 80.1, early: 1.3, indeterminate: 0.4 },
    noToolCallTurns: { onTime: 65.5, late: 32.0, early: 2.2, indeterminate: 0.2 },
    latePctWithToolCalls: 80.1,
    latePctWithoutToolCalls: 32.0,
    latePctDifference: 48.1,
    lateTurnBreakdown: { withToolCalls: 77.5, withoutToolCalls: 22.5 },
  },
  {
    systemId: 'parakeet-ctc-1-1b-gpt-oss-120b-kokoro',
    allTurns: { onTime: 35.6, late: 63.0, early: 1.2, indeterminate: 0.3 },
    toolCallTurns: { onTime: 14.0, late: 85.1, early: 0.6, indeterminate: 0.3 },
    noToolCallTurns: { onTime: 53.1, late: 45.0, early: 1.7, indeterminate: 0.2 },
    latePctWithToolCalls: 85.1,
    latePctWithoutToolCalls: 45.0,
    latePctDifference: 40.1,
    lateTurnBreakdown: { withToolCalls: 60.6, withoutToolCalls: 39.4 },
  },
  {
    systemId: 'gpt-4o-mini-transcribe-gpt-5-mini-gpt-4o-mini-tts',
    allTurns: { onTime: 29.1, late: 68.4, early: 2.4, indeterminate: 0.2 },
    toolCallTurns: { onTime: 5.6, late: 93.9, early: 0.5, indeterminate: 0.0 },
    noToolCallTurns: { onTime: 48.4, late: 47.4, early: 3.9, indeterminate: 0.3 },
    latePctWithToolCalls: 93.9,
    latePctWithoutToolCalls: 47.4,
    latePctDifference: 46.5,
    lateTurnBreakdown: { withToolCalls: 61.9, withoutToolCalls: 38.1 },
  },
  {
    systemId: 'parakeet-ctc-1-1b-qwen3-5-27b-kokoro',
    allTurns: { onTime: 22.7, late: 75.6, early: 0.9, indeterminate: 0.8 },
    toolCallTurns: { onTime: 6.3, late: 92.1, early: 1.0, indeterminate: 0.6 },
    noToolCallTurns: { onTime: 48.2, late: 50.2, early: 0.6, indeterminate: 1.0 },
    latePctWithToolCalls: 92.1,
    latePctWithoutToolCalls: 50.2,
    latePctDifference: 41.9,
    lateTurnBreakdown: { withToolCalls: 74.0, withoutToolCalls: 26.0 },
  },
  {
    systemId: 'voxtral-mini-3b-gpt-oss-120b-chatterbox-turbo',
    allTurns: { onTime: 20.4, late: 77.4, early: 2.2, indeterminate: 0.0 },
    toolCallTurns: { onTime: 13.3, late: 84.9, early: 1.8, indeterminate: 0.0 },
    noToolCallTurns: { onTime: 24.4, late: 73.2, early: 2.4, indeterminate: 0.0 },
    latePctWithToolCalls: 84.9,
    latePctWithoutToolCalls: 73.2,
    latePctDifference: 11.7,
    lateTurnBreakdown: { withToolCalls: 39.4, withoutToolCalls: 60.6 },
  },
  {
    systemId: 'whisper-large-v3-gpt-oss-20b-chatterbox-turbo',
    allTurns: { onTime: 18.9, late: 78.5, early: 2.3, indeterminate: 0.3 },
    toolCallTurns: { onTime: 10.7, late: 85.9, early: 2.9, indeterminate: 0.4 },
    noToolCallTurns: { onTime: 25.3, late: 72.7, early: 1.9, indeterminate: 0.2 },
    latePctWithToolCalls: 85.9,
    latePctWithoutToolCalls: 72.7,
    latePctDifference: 13.3,
    lateTurnBreakdown: { withToolCalls: 47.8, withoutToolCalls: 52.2 },
  },
  {
    systemId: 'gpt-4o-mini-transcribe-sonnet-4-6-gpt-4o-mini-tts',
    allTurns: { onTime: 10.8, late: 88.3, early: 0.7, indeterminate: 0.2 },
    toolCallTurns: { onTime: 0.0, late: 99.5, early: 0.2, indeterminate: 0.2 },
    noToolCallTurns: { onTime: 18.3, late: 80.4, early: 1.1, indeterminate: 0.2 },
    latePctWithToolCalls: 99.5,
    latePctWithoutToolCalls: 80.4,
    latePctDifference: 19.1,
    lateTurnBreakdown: { withToolCalls: 46.5, withoutToolCalls: 53.5 },
  },
  {
    systemId: 'parakeet-ctc-1-1b-gpt-oss-120b-chatterbox-turbo',
    allTurns: { onTime: 7.0, late: 90.4, early: 2.6, indeterminate: 0.0 },
    toolCallTurns: { onTime: 2.0, late: 96.2, early: 1.7, indeterminate: 0.0 },
    noToolCallTurns: { onTime: 10.6, late: 86.2, early: 3.2, indeterminate: 0.0 },
    latePctWithToolCalls: 96.2,
    latePctWithoutToolCalls: 86.2,
    latePctDifference: 10.1,
    lateTurnBreakdown: { withToolCalls: 45.0, withoutToolCalls: 55.0 },
  },
  {
    systemId: 'voxtral-mini-3b-qwen3-5-27b-chatterbox-turbo',
    allTurns: { onTime: 3.1, late: 92.1, early: 4.6, indeterminate: 0.2 },
    toolCallTurns: { onTime: 0.8, late: 94.7, early: 4.0, indeterminate: 0.4 },
    noToolCallTurns: { onTime: 5.1, late: 89.7, early: 5.1, indeterminate: 0.0 },
    latePctWithToolCalls: 94.7,
    latePctWithoutToolCalls: 89.7,
    latePctDifference: 5.0,
    lateTurnBreakdown: { withToolCalls: 49.0, withoutToolCalls: 51.0 },
  },
  {
    systemId: 'parakeet-ctc-1-1b-qwen3-5-27b-chatterbox-turbo',
    allTurns: { onTime: 2.3, late: 94.5, early: 2.6, indeterminate: 0.5 },
    toolCallTurns: { onTime: 0.4, late: 97.3, early: 1.9, indeterminate: 0.4 },
    noToolCallTurns: { onTime: 4.4, late: 91.5, early: 3.5, indeterminate: 0.7 },
    latePctWithToolCalls: 97.3,
    latePctWithoutToolCalls: 91.5,
    latePctDifference: 5.8,
    lateTurnBreakdown: { withToolCalls: 54.2, withoutToolCalls: 45.8 },
  },
];
